[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.3"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=6.30.1",
    "openai>=1.109.1",
]
